### ISSUE TITLE
fails in jsdom environment

### ISSUE THREAD

**Issue by diachedelic** [fergaldoyle/vue-form#127]
I am trying to unit test a component which uses `vue-form`, but I am getting runtime errors during the component lifecycle of `<vue-form>` (I think).  Seems to be related to https://github.com/vuejs/vue/issues/10554 and https://github.com/vuejs/vue/issues/8350

Relevant packages:
* vue@2.6.10
* vue-form@4.10.1
* mocha-webpack@2.0.0-beta.0
* jsdom@15.1.1

```
VM3741 main.js:57169 TypeError: Cannot read property '$scopedSlots' of undefined
    at updateChildComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4103:1)
    at prepatch (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:3125:1)
    at patchVnode (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:6302:1)
    at VueComponent.patch [as __patch__] (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:6476:1)
    at VueComponent.Vue._update (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:3942:1)
    at VueComponent.updateComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4060:1)
    at Watcher.get (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4473:1)
    at Watcher.run (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4548:1)
    at flushSchedulerQueue (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4304:1)
    at queueWatcher (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4393:1)
    at Watcher.update (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4538:1)
    at Dep.notify (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:730:1)
    at VueComponent.set [as $set] (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:1093:1)
    at /Users/me/Code/proj-vue-shared/node_modules/vue-form/dist/vue-form.js:571:1
    at Array.forEach (<anonymous>)
    at VueComponent.created (/Users/me/Code/proj-vue-shared/node_modules/vue-form/dist/vue-form.js:570:1)
    at invokeWithErrorHandling (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:1854:1)
    at callHook (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4213:1)
    at VueComponent.Vue._init (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:5002:1)
    at new VueComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:5148:1)
    at createComponentInstanceForVnode (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:3283:1)
    at init (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:3114:1)
    at createComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:5972:1)
    at createElm (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:5919:1)
    at VueComponent.patch [as __patch__] (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:6471:1)
    at VueComponent.Vue._update (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:3939:1)
    at VueComponent.updateComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4060:1)
    at Watcher.get (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4473:1)
    at new Watcher (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4462:1)
    at mountComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4067:1)
    at VueComponent../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:8409:1)
    at init (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:3118:1)
    at createComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:5972:1)
    at createElm (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:5919:1)
    at VueComponent.patch [as __patch__] (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:6471:1)
    at VueComponent.Vue._update (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:3939:1)
    at VueComponent.updateComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4060:1)
    at Watcher.get (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4473:1)
    at new Watcher (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4462:1)
    at mountComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4067:1)
    at VueComponent../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:8409:1)
    at mount (/Users/me/Code/proj-vue-shared/node_modules/@vue/test-utils/dist/vue-test-utils.js:8649:1)
    at Context.it (/Users/me/Code/proj-vue-shared/test/unit/login-form.js:76:1)
    at callFn (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runnable.js:387:21)
    at Test.Runnable.run (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runnable.js:379:7)
    at Runner.runTest (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:535:10)
    at /Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:653:12
    at next (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:447:14)
    at /Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:457:7
    at next (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:362:14)
    at Immediate._onImmediate (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:425:5)
    at processImmediate (internal/timers.js:443:21)
```

![image](https://user-images.githubusercontent.com/310464/65943258-61386000-e472-11e9-911b-60d0337a6013.png)

And another error is emitted but I can only assume it's caused by the first one:
```
VM3741 main.js:57169 TypeError: this.formstate._addControl is not a function
    at VueComponent.mounted (/Users/me/Code/proj-vue-shared/node_modules/vue-form/dist/vue-form.js:853:1)
    at invokeWithErrorHandling (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:1854:1)
    at callHook (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4213:1)
    at Object.insert (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:3139:1)
    at invokeInsertHook (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:6340:1)
    at VueComponent.patch [as __patch__] (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:6559:1)
    at VueComponent.Vue._update (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:3939:1)
    at VueComponent.updateComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4060:1)
    at Watcher.get (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4473:1)
    at new Watcher (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4462:1)
    at mountComponent (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:4067:1)
    at VueComponent../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (/Users/me/Code/proj-vue-shared/node_modules/vue/dist/vue.runtime.esm.js:8409:1)
    at mount (/Users/me/Code/proj-vue-shared/node_modules/@vue/test-utils/dist/vue-test-utils.js:8649:1)
    at Context.it (/Users/me/Code/proj-vue-shared/test/unit/login-form.js:76:1)
    at callFn (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runnable.js:387:21)
    at Test.Runnable.run (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runnable.js:379:7)
    at Runner.runTest (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:535:10)
    at /Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:653:12
    at next (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:447:14)
    at /Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:457:7
    at next (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:362:14)
    at Immediate._onImmediate (/Users/me/Code/proj-vue-shared/node_modules/mocha/lib/runner.js:425:5)
    at processImmediate (internal/timers.js:443:21)
```

**Comment by diachedelic** [comment]
The line in vue-form which causes the first error is in the `vueForm` created hook, here:

![image](https://user-images.githubusercontent.com/310464/65943573-208d1680-e473-11e9-8361-54b2e3010603.png)

**Comment by chrisnicola** [comment]
Are you running this with vue-test-utils? I believe you might be running into this problem: https://github.com/vuejs/vue-test-utils/issues/1130

This was what fixed it for me (unfortunately). You can also try rolling back the version of vue-test-utils as this bug was only introduced in the last beta release. https://github.com/vuejs/vue-test-utils/issues/1130#issuecomment-536012029

**Comment by diachedelic** [comment]
@chrisnicola yes that was the issue! I upgraded vue-test-utils to the latest beta and modified my tests appropriately
